# ============================================================================
# 前端扫描匹配器配置 (Scan Matcher Configuration)
# ============================================================================
scan_matcher:
  ros__parameters:
    # --------------------------------------------------------------------------
    # 坐标系配置 (Frame Configuration)
    # --------------------------------------------------------------------------
    global_frame_id: "odom"          # 全局坐标系ID，通常为odom或map
    robot_frame_id: "base_link"      # 机器人本体坐标系ID
    
    # --------------------------------------------------------------------------
    # 配准算法配置 (Registration Algorithm Configuration)
    # --------------------------------------------------------------------------
    registration_method: "NDT"        # 配准方法："NDT"或"GICP"
                                      # NDT: 正态分布变换，适合结构化环境
                                      # GICP: 广义ICP，适合特征丰富环境
    
    # NDT算法参数 (NDT Algorithm Parameters)
    ndt_resolution: 2.0               # NDT网格分辨率(米)，影响配准精度和速度
                                      # 较小值(1.0-2.0)：高精度，计算量大
                                      # 较大值(3.0-5.0)：低精度，计算量小
    ndt_num_threads: 4                # NDT并行线程数，建议设为CPU核心数
                                      # 增加线程数可提高处理速度
    
    # GICP算法参数 (GICP Algorithm Parameters)
    gicp_corr_dist_threshold: 5.0     # GICP对应点距离阈值(米)
                                      # 超过此距离的点对不参与配准
    
    # --------------------------------------------------------------------------
    # 地图更新策略 (Map Update Strategy)
    # --------------------------------------------------------------------------
    trans_for_mapupdate: 1.5          # 触发地图更新的平移距离阈值(米)
                                      # 机器人移动超过此距离时更新局部地图
                                      # 较小值：地图更新频繁，精度高，计算量大
                                      # 较大值：地图更新稀疏，精度低，计算量小
    
    # --------------------------------------------------------------------------
    # 点云预处理配置 (Point Cloud Preprocessing)
    # --------------------------------------------------------------------------
    vg_size_for_input: 0.5            # 输入点云体素滤波尺寸(米)
                                      # 用于降采样输入激光雷达数据
                                      # 较小值：保留更多细节，计算量大
                                      # 较大值：数据压缩更多，计算量小
    
    vg_size_for_map: 0.1              # 地图点云体素滤波尺寸(米)
                                      # 用于降采样累积的地图点云
                                      # 影响地图存储大小和配准精度
    
    use_min_max_filter: true          # 是否启用距离滤波
                                      # 过滤掉过近和过远的点云数据
    
    # --------------------------------------------------------------------------
    # 激光雷达数据配置 (LiDAR Data Configuration)
    # --------------------------------------------------------------------------
    scan_min_range: 1.0               # 激光雷达最小有效距离(米)
                                      # 过滤掉过近的噪声点
                                      # rslidar建议设置为0.5-2.0米
    
    scan_max_range: 100.0             # 激光雷达最大有效距离(米)
                                      # 过滤掉过远的不可靠点
                                      # rslidar建议根据实际测距能力设置
    
    scan_period: 0.1                  # 激光雷达扫描周期(秒)
                                      # rslidar通常为10Hz，即0.1秒
                                      # 根据实际激光雷达频率调整
    
    # --------------------------------------------------------------------------
    # 发布和显示配置 (Publishing and Display Configuration)
    # --------------------------------------------------------------------------
    map_publish_period: 10.0          # 地图发布周期(秒)
                                      # 控制地图点云的发布频率
                                      # 较小值：实时性好，网络负载大
                                      # 较大值：实时性差，网络负载小
    
    num_targeted_cloud: 20            # 用于配准的目标点云帧数
                                      # 影响局部地图的大小和配准稳定性
                                      # 较大值：配准更稳定，内存占用大
    
    # --------------------------------------------------------------------------
    # 初始位姿配置 (Initial Pose Configuration)
    # --------------------------------------------------------------------------
    set_initial_pose: true            # 是否设置初始位姿
                                      # 建议在已知起始位置时设为true
    
    initial_pose_x: 0.0               # 初始位置X坐标(米)
    initial_pose_y: 0.0               # 初始位置Y坐标(米)
    initial_pose_z: 0.0               # 初始位置Z坐标(米)
    initial_pose_qx: 0.0              # 初始姿态四元数X分量
    initial_pose_qy: 0.0              # 初始姿态四元数Y分量
    initial_pose_qz: 0.0              # 初始姿态四元数Z分量
    initial_pose_qw: 1.0              # 初始姿态四元数W分量
    
    # --------------------------------------------------------------------------
    # 传感器融合配置 (Sensor Fusion Configuration)
    # --------------------------------------------------------------------------
    use_imu: false                    # 是否使用IMU数据
                                      # 如果有IMU可设为true提高精度
    
    use_odom: false                   # 是否使用里程计数据
                                      # 仅使用激光雷达时设为false
                                      # 有轮式里程计时可设为true
    
    # --------------------------------------------------------------------------
    # TF变换配置 (TF Transform Configuration)
    # --------------------------------------------------------------------------
    tf_tolerance: 0.2                 # TF查询容忍时间(秒)
                                      # 解决时间同步问题的关键参数
                                      # 出现TF错误时可适当增大此值
    
    use_latest_tf: true               # 使用最新可用的TF变换
                                      # 有助于解决时间同步问题
    
    tf_timeout: 0.1                   # TF查询超时时间(秒)
    
    # --------------------------------------------------------------------------
    # 调试配置 (Debug Configuration)
    # --------------------------------------------------------------------------
    debug_flag: false                 # 是否启用调试模式
                                      # 启用后会输出详细的调试信息

# ============================================================================
# 后端图优化配置 (Graph-based SLAM Backend Configuration)
# ============================================================================
graph_based_slam:
    ros__parameters:
      # ------------------------------------------------------------------------
      # 配准算法配置 (Registration Algorithm Configuration)
      # ------------------------------------------------------------------------
      registration_method: "NDT"      # 后端使用的配准方法
                                      # 建议与前端保持一致
      
      ndt_resolution: 1.0             # 后端NDT分辨率(米)
                                      # 通常比前端更精细，用于回环检测
      
      ndt_num_threads: 4              # 后端NDT线程数
                                      # 建议设为CPU核心数
      
      # ------------------------------------------------------------------------
      # 点云处理配置 (Point Cloud Processing Configuration)
      # ------------------------------------------------------------------------
      voxel_leaf_size: 0.1            # 体素滤波叶子大小(米)
                                      # 用于后端点云降采样
      
      # ------------------------------------------------------------------------
      # 回环检测配置 (Loop Closure Detection Configuration)
      # ------------------------------------------------------------------------
      loop_detection_period: 2000     # 回环检测周期(毫秒)
                                      # 控制回环检测的频率
                                      # 较小值：检测频繁，计算量大
                                      # 较大值：检测稀疏，可能错过回环
      
      threshold_loop_closure_score: 0.6  # 回环检测得分阈值
                                         # 判断是否构成回环的相似度阈值
                                         # 较小值：容易检测到回环，可能误检
                                         # 较大值：严格检测回环，可能漏检
      
      distance_loop_closure: 50.0     # 回环检测距离阈值(米)
                                      # 只有距离超过此值的位置才考虑回环
                                      # 避免短距离的错误回环检测
      
      range_of_searching_loop_closure: 15.0  # 回环搜索范围(米)
                                             # 在此范围内搜索潜在的回环候选
      
      search_submap_num: 3            # 搜索的子地图数量
                                      # 用于回环检测的历史子地图数量
      
      # ------------------------------------------------------------------------
      # 图优化配置 (Graph Optimization Configuration)
      # ------------------------------------------------------------------------
      num_adjacent_pose_cnstraints: 5 # 相邻位姿约束数量
                                      # 与相邻多少个位姿建立约束关系
                                      # 影响图优化的稳定性
      
      # ------------------------------------------------------------------------
      # 地图保存配置 (Map Saving Configuration)
      # ------------------------------------------------------------------------
      use_save_map_in_loop: true      # 是否在回环时保存地图
                                      # 启用后会在检测到回环时自动保存
      
      # ------------------------------------------------------------------------
      # 调试配置 (Debug Configuration)
      # ------------------------------------------------------------------------
      debug_flag: false               # 是否启用后端调试模式
                                      # 启用后输出图优化的详细信息